name: "kvm-check"
on:
  workflow_dispatch:
  schedule:
    # every Wednesday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 3"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.23.2'
permissions:
  contents: read

jobs:
  kvm-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: kvm-check
        run: |
          egrep -c '(vmx|svm)' /proc/cpuinfo
          sudo apt-get install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sudo adduser `id -un` libvirt
          sudo adduser `id -un` kvm
          virsh list --all
