name: "update-leaderboard"
on:
  workflow_dispatch:
  push:
    tags-ignore:
      - 'v*-beta.*'
  release:
    types: [published]
env:
  GO_VERSION: '1.18.2'
permissions:
  contents: read

jobs:
  update-leaderboard:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923
        with:
          go-version: ${{env.GO_VERSION}}
          stable: true
      - name: Update Leaderboard
        id: leaderboard
        run: |
          make update-leaderboard
          c=$(git status --porcelain)
          c="${c//$'\n'/'%0A'}"
          c="${c//$'\r'/'%0D'}"
          echo "::set-output name=changes::$c"
        env:
          GITHUB_TOKEN: ${{ secrets.MINIKUBE_BOT_PAT }}
      - name: Create PR
        if: ${{ steps.leaderboard.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@f094b77505fb89581e68a1163fbd2fffece39da1
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: Update leaderboard
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: leaderboard
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Update leaderboard'
          body: |
            Committing changes resulting from `make update-leaderboard`.
            This PR is auto-generated by the [update-leaderboard](https://github.com/kubernetes/minikube/blob/master/.github/workflows/leaderboard.yml) CI workflow.

            ```
            ${{ steps.leaderboard.outputs.changes }}
            ```
