name: kvm
on:
  workflow_dispatch:

jobs:
  kvm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
      - run: |
          sudo apt update && sudo apt install -y qemu qemu-user-static
      - uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18
      - uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c
      - run: |
          MINIKUBE_BUILD_IN_DOCKER=y make out/docker-machine-driver-kvm2-arm64
