name: "time-to-k8s benchmark"
on:
  pull_request:
    types: [opened]
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: 1.16.5
  TAG: v4.4.4
jobs:
  benchmark:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init
    - uses: actions/setup-go@v2
      with:
          go-version: ${{env.GO_VERSION}}
          stable: true
    - name: Benchmark
      run: |
          ./hack/benchmark/time-to-k8s/time-to-k8s.sh ${{ secrets.ACCESS_TOKEN }}
