name: "time-to-k8s benchmark"
on:
  workflow_dispatch:
  release:
    types: [released]
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.19.2'
permissions:
  contents: read

jobs:
  benchmark:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - name: Checkout submodules
      run: git submodule update --init
    - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
      with:
          go-version: ${{env.GO_VERSION}}
    - name: time-to-k8s Benchmark
      id: timeToK8sBenchmark
      run: |
          ./hack/benchmark/time-to-k8s/time-to-k8s.sh
          echo "::set-output name=version::$(minikube version --short)"
    - name: Create PR
      uses: peter-evans/create-pull-request@ad43dccb4d726ca8514126628bec209b8354b6dd
      with:
        token: ${{ secrets.MINIKUBE_BOT_PAT }}
        commit-message: add time-to-k8s benchmark for ${{ steps.timeToK8sBenchmark.outputs.version }}
        committer: minikube-bot <minikube-bot@google.com>
        author: minikube-bot <minikube-bot@google.com>
        branch: addTimeToK8s${{ steps.timeToK8sBenchmark.outputs.version }}
        push-to-fork: minikube-bot/minikube
        base: master
        delete-branch: true
        title: Add time-to-k8s benchmark for ${{ steps.timeToK8sBenchmark.outputs.version }}
        body: Updating time-to-k8s benchmark as part of the release process
