name: "update-golint-version"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.18'
permissions:
  contents: read

jobs:
  bump-golint-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
        with:
          go-version: ${{env.GO_VERSION}}
          stable: true
      - name: Bump Golint Versions
        id: bumpGolint
        run: |
          make update-golint-version
          echo "::set-output name=changes::$(git status --porcelain)"
      - name: Create PR
        if: ${{ steps.bumpGolint.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@bd72e1b7922d417764d27d30768117ad7da78a0e
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: bump golint versions
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_golint_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'bump golint version'
          labels: ok-to-test
          body: |
            Golangci-lint Project release a [new version](https://github.com/golangci/golangci-lint/releases),

            This PR was auto-generated by `make update-golint-version` using [update-golint-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-golint-version.yml) CI Workflow. 

                   
            
            
