name: "update-kubernetes-versions"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 1 am pacific/8 am UTC
    - cron: "0 8 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.17.7'
permissions:
  contents: read

jobs:
  bump-k8s-versions:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: ${{env.GO_VERSION}}
          stable: true
      - name: Bump Kuberenetes Versions
        id: bumpk8s
        run: |
          t=$(make update-kubernetes-version)
          t=$(echo $t | head -n 1)
          echo "::set-output name=title::$t"
          c=$(git status --porcelain)
          c="${c//$'\n'/'%0A'}"
          c="${c//$'\r'/'%0D'}"
          echo "::set-output name=changes::$c"
      - name: Create PR
        if: ${{ steps.bumpk8s.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@d6d5519d05f5814158ef015b8448f2f74648c421 # v3
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: bump default/newest kubernetes versions
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_k8s_versions
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: "${{ steps.bumpk8s.outputs.title }}"
          labels: ok-to-test
          body: |
            This PR was auto-generated by `make update-kubernetes-version` using [update-k8s-versions.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows) CI Workflow. 
            Please only merge if all the tests pass.

            ```
            ${{ steps.bumpk8s.outputs.changes }}
            ```
