name: "update-gotestsum-version"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.19.1'
permissions:
  contents: read

jobs:
  bump-gotestsum-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Bump Gotestsum Versions
        id: bumpGotestsum
        run: |
          make update-gotestsum-version
          echo "::set-output name=changes::$(git status --porcelain)"
      - name: Create PR
        if: ${{ steps.bumpGotestsum.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@671dc9c9e0c2d73f07fa45a3eb0220e1622f0c5f
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: bump gotestsum versions
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_gotestsum_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'bump gotestsum version'
          labels: ok-to-test
          body: |
            Gotestsum Project release a [new version](https://github.com/gotestyourself/gotestsum/releases),

            This PR was auto-generated by `make update-gotestsum-version` using [update-gotestsum-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-gotestsum-version.yml) CI Workflow.
